
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: jmaisiba/yolo_client_image:v1.1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
