
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-pvc
  labels:
    app: mongo
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
